### ISSUE TITLE
3015 (instead of 2015) item

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitrpg-shared#439]
There are several items in locales/en/gear.json where the description says 3015 instead of 2015

**Comment by Alys** [comment]
3015 is correct. It's the [Mysterious Time Travelers](http://habitrpg.wikia.com/wiki/Mysterious_Time_Travelers) gear.

**Comment by paglias** [comment]
@Alys thanks

**Comment by paglias** [comment]
I received a report about this on Transifex, I thought it was an error, at least I didn't make any change :)

**Comment by Alys** [comment]
Good call! :)
